### ISSUE TITLE
STL export not working

### ISSUE THREAD

**Issue by HSN1426** [Alistairj43/TPMS-Designer#1]
Hi, 
First and foremost, I'd like to thank you for making this tool available. However, I cannot generate an STL file using the command "myTPMS.FV.exportSTL('outputs/myTPMS.stl')" as shown in the documentation file "Ex1SingleTPMS.mlx". The corresponding error I get is "Unable to resolve the name 'myTPMS.FV.exportSTL'.". I've reviewed the solutions online but didn't have any success; the most prominent solution can be accessed from this link "https://uk.mathworks.com/matlabcentral/answers/480267-error-unable-to-resolve-name-issue". Is there a file missing from the repository that is needed for this function to work? 

Also, I encounter an error when the following function is used (again when running the provided documentation):

- axesHist = myCell.plot("histogram","inclination angle");
The corresponding errors are:

- Unrecognized method, property, or field 'Fproperty' for class 'UnitCell'.

   Error in [plotHistogram](matlab:matlab.internal.language.introspective.errorDocCallback('plotHistogram', 
   'C:\Users\User\AppData\Roaming\MathWorks\MATLAB Add-Ons\Collections\TPMS Designer\dependancies\plotHistogram.m', 35)) 
   ([line 35](matlab: opentoline('C:\Users\User\AppData\Roaming\MathWorks\MATLAB Add-Ons\Collections\TPMS       
   Designer\dependancies\plotHistogram.m',35,0)))
   elseif isfield(data.Fproperty,pID) % Face Property

   Error in [UnitCell/plot](matlab:matlab.internal.language.introspective.errorDocCallback('UnitCell/plot', 
   'C:\Users\User\AppData\Roaming\MathWorks\MATLAB Add-Ons\Collections\TPMS Designer\classes\UnitCell.m', 194)) ([line 194] 
   (matlab: opentoline('C:\Users\User\AppData\Roaming\MathWorks\MATLAB Add-Ons\Collections\TPMS 
   Designer\classes\UnitCell.m',194,0)))
                    h = plotHistogram(UnitCell,property1,opts,ax);

Also, apologies if I'm using the incorrect terminology, as I'm relatively new to MATLAB, and I'm only using it for my final year project.

Could you please get back to me as soon as possible because I'd like to use this toolbox for my final year project however I'm running out of time.

Kind regards,
Hassan.

**Comment by Alistairj43** [comment]
Hi Hassan,

Thanks for your interest in the toolbox.


Regarding the export error this is because the "myTPMS" variable was
changed to "myCell" in my latest version, but I failed to update this line
which was commented out. As long as you didn't change anything else you
should be able do make the following change to the example file: (You may
also want to/need to change the string for the filename/path)

the line that reads:
%myTPMS.FV.exportSTL('outputs/myTPMS.stl'); % STL Export (path+filename)

Should actually be:
myCell.FV.exportSTL('outputs/myTPMS.stl'); % STL Export (path+filename)


Regarding the second error - this looks like another bug which i had
thought i already fixed as part of the latest version.
It is an error in my "plotHistogram" function, I will look into it later
this week and update the files if I get time -> but as a work-around you
could try the following change to plotHistogram:

This section of the code:
if isfield(data,pID) % FV General Property
x_in = data.(pID);
elseif isfield(data.Fproperty,pID) % Face Property
x_in = data.Fproperty.(pID);
try
a_in = data.Fproperty.area;
catch
a_in = ones(size(x_in)); % Face areas not found
end
elseif isfield(data.Vproperty,pID) % Vertex Property
x_in = data.Vproperty.(pID);
a_in = ones(size(x_in));
else
x_in = [0 1];
a_in = ones(size(x_in));
pName = "Data not found";
end

Needs to be moved up a few lines to here:
elseif isfield(data,'FV')
data = data.FV;
*<INSERT HERE>*
end

Hopefully you find this helpful, Cheers,
Alistair

**Comment by HSN1426** [comment]
Hi Alistair,

Thank you for providing a quick solution. The STLs are working now although I'm yet to try the provided code. 
The help was very much appreciated.

Best wishes,
Hassan.
