### ISSUE TITLE
Cylindrical Scaffolds with gradient porosities

### ISSUE THREAD

**Issue by HSN1426** [Alistairj43/TPMS-Designer#2]
Hi Alistair,

I'm not sure if this is a problem with the toolbox or just my code, but I was wondering whether it was possible to create cylindrical scaffolds with gradient porosities with the "TPMS Designer" toolbox. I've checked the documentation, and I could see that various methods have been listed in the "bulkSize.m" file (box, cylinder, FV), but only the box method is currently working. In addition, the documentation states that the properties must be stated as a vector of size (Lx1) or a matrix for 2D and 3D gradients, all of which I've tried. Also, how would I generate a closed volume as I need to create a solid from the exported STL?

I've been trying to figure the above out, but none of my attempts are working. If it is an error with my code, would you be interested in providing training? I'm relatively new to MATLAB and this toolbox, and I'm not very skilled at it yet.
If you're interested, I'll be willing to pay £40/hour of training. If not, would it be possible for you to provide a sample code to generate cylindrical scaffolds with gradient porosities (radially and in the X, Y, & Z directions)?

Best wishes,
Hassan.

**Comment by Alistairj43** [comment]
Hi Hassan,

It is possible to create, in my private testing codes I had previously
generated and printed exactly the type of structure you describe. For
integrating to the toolbox/app, the issue is more - how nicely integrate
into the toolbox, without making the UI/commands over-complicated.
Below is an image of some gradient structures I was messing around with and
3D printed.

![Graded TPMS](https://user-images.githubusercontent.com/39683918/215923995-8ec6a0fa-d77b-4ac2-9131-90564c7a8606.jpg)

In terms of training, I would be happy to meet with you online to
discuss/help you work through how you could achieve this. What time/date
might you be looking at?

Cheers
Alistair

**Comment by HSN1426** [comment]
Hi Alistair,

Thank you for the clarification. Regarding the online meeting, my availability is as follows:

Thursday 2nd Feb: 08:00 - 12:00 & 17:00 - 23:00
Friday 3rd Feb: 08:00 - 11:00 & 15:00 - 23:00
Weekend - any time

I'd prefer to meet during the weekdays, as I need to make some progress for my project. The times listed are in GMT. If the aforementioned times are inconvenient, just let me know, so another time can be arranged, as my schedule is pretty flexible. As for the payment, would PayPal be fine?

Furthermore, would it be ok if the meeting were to take place on Microsoft teams? My email is hassanahmad1426@gmail.com.

I look forward to the meeting.
All the best,
Hassan.

**Comment by Alistairj43** [comment]
Following this I have been working on adding functionality to use different fundamental shapes (cylinder/ellipsoid) as well as an object (.stl) to define the bounding/trimming shape.

This should make this easier to apply structures/tune them in the future for both the GUI and the code-line toolbox.

![image](https://user-images.githubusercontent.com/39683918/216503504-0e07763c-5a90-4ee4-8114-5241332bf655.png)


![image](https://user-images.githubusercontent.com/39683918/216503366-e89dcdd0-26e8-41ff-9267-8fa7cb0c4b65.png)


Support for gradients (input using a vector for volume fraction 'V1/V2' information) has also been added.
