### ISSUE TITLE
import of .stl

### ISSUE THREAD

**Issue by BearBroendum** [Alistairj43/TPMS-Designer#3]
Hi Alistair.

I have just downloaded the TPMSDesigner_Installer_web.exe package and it seems, after a quick bit of messing around, to be pretty easy to use. 

I do, however, not find the choice of .stl in the "size method"-column available in the GUI.

Am I missing something in the install or does this particular version not support this feature?

Thanks in advance.

**Comment by Alistairj43** [comment]
Hi, I Have been testing the feature through the toolbox/app to this point
and have not made a new stand-alone/.exe version for it yet as there are
still some things I need to tweak with how the import works. It will
however be part of the next version. - Likely released around the end of
Feb.

Cheers

**Comment by BearBroendum** [comment]
Ah, okay. so that´s whats up. Now I understand....

So the app for Matlab is capable of importing .stl´s? Or am I not understanding you correctly?

No matter what, I´ll be looking forward to a version with that ability, because you have made an exelent job at putting this great designer tool together. I´ve tried several other TPMS-generators from Github ect. and this is by far the most userfriendly I have tried. Huge thumbs-up!

**Comment by Alistairj43** [comment]
Yes, the .mlapp should have that added already, although it is still a bit tricky to make it work properly. So I haven't gotten to exporting it to the standalone/exe version.

The issues are mostly issues around creating the right voxel sizing/unit cell sizing so the final part doesn't change size, crash because the resolution is too high resolution, or have unit cells larger than the part.

I've also been testing 2 methods, one doing the boolean on the implicit model (requires converting the .stl to an implicit) the other generating unit cells for the whole stl bounding box then using a mesh-boolean which would potentially give better results (but I don't have a nice Matlab function for mesh boolean yet, and it potentially creates other issues).


Thanks! Having a clean (fairly simple) interface was one of the major focuses for the app, so its nice to hear you found it user friendly.

If there's any other features/functions that would be helpful please let me know. (No promises, but I'm always looking for ideas on improving it)

Cheers
Alistair

________________________________

**Comment by BearBroendum** [comment]
Now that you mention it:

Another great feature would be a graded lattice form. It could be very useful in e.g cones where a smaller cell structure in the narrow end is desired to give the finished .stl a more uniform finish towards the outer edges. 

Or it could also be used for changing the center of mass on a cone or some other non-uniform part.

That could be a great feature.

Thanks again, Alistair, and I´m looking forward to the next great versions coming up.

**Comment by Alistairj43** [comment]
The stl import issue has been fixed.
